"""
Static disease-symptom knowledge base used to train the ML model.
Each entry: disease name, specKey, severity, list of symptoms/keywords.
"""

DISEASE_DATA = [
    # General
    {
        "disease": "Common Cold",
        "specKey": "general",
        "severity": "mild",
        "description": "A viral infection of the upper respiratory tract.",
        "symptoms": ["runny nose", "sore throat", "sneezing", "cough", "mild fever", "congestion",
                     "headache", "fatigue", "watery eyes", "nasal discharge"],
    },
    {
        "disease": "Influenza (Flu)",
        "specKey": "general",
        "severity": "moderate",
        "description": "A highly contagious viral respiratory illness.",
        "symptoms": ["high fever", "chills", "body aches", "muscle pain", "fatigue", "headache",
                     "cough", "sore throat", "runny nose", "vomiting", "diarrhea,"],
    },
    {
        "disease": "Typhoid Fever",
        "specKey": "general",
        "severity": "moderate",
        "description": "A bacterial infection that can spread throughout the body.",
        "symptoms": ["sustained fever", "weakness", "abdominal pain", "headache", "loss of appetite",
                     "diarrhea", "constipation", "rose spots", "enlarged spleen"],
    },
    {
        "disease": "Dengue Fever",
        "specKey": "general",
        "severity": "moderate",
        "description": "A mosquito-borne viral infection causing severe flu-like illness.",
        "symptoms": ["high fever", "severe headache", "pain behind eyes", "joint pain", "muscle pain",
                     "rash", "mild bleeding", "nausea", "vomiting", "bone pain", "dengue"],
    },
    {
    "disease": "Food Poisoning",
    "specKey": "general",
    "severity": "mild",
    "description": "Illness caused by contaminated food or drink.",
    "symptoms": [
        "nausea", "vomiting",  "diarrhea","diarrhea","stomach pain", "abdominal cramps",]
},
{
    "disease": "Electric Shock",
    "specKey": "general",
    "severity": "moderate",
    "description": "Injury caused by electric current.",
    "symptoms": [
        "electric shock","electrik shock","burn","pain","muscle pain"],
},
    # Cardiology
    {
        "disease": "Hypertension (High Blood Pressure)",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "Persistently elevated blood pressure in the arteries.",
        "symptoms": ["headache", "dizziness", "blurred vision", "chest pain", "shortness of breath",
                     "high blood pressure", "nose bleed", "palpitations"],
    },
    {
        "disease": "Heart Attack",
        "specKey": "cardio",
        "severity": "emergency",
        "description": "Blockage of blood flow to the heart muscle.",
        "symptoms": ["chest pain", "crushing chest pain", "left arm pain", "jaw pain",
                     "shortness of breath", "sweating", "nausea", "dizziness", "heart attack",
                     "chest pressure", "pain radiating"],
    },
    {
        "disease": "Angina",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "Chest pain caused by reduced blood flow to the heart.",
        "symptoms": ["chest pain", "tightness in chest", "pressure in chest", "pain in shoulder",
                     "pain in arm", "shortness of breath", "dizziness", "nausea", "fatigue"],
    },
    {
        "disease": "Heart Failure",
        "specKey": "cardio",
        "severity": "emergency",
        "description": "The heart does not pump blood as well as it should.",
        "symptoms": ["shortness of breath", "swollen legs", "swollen ankles", "fatigue",
                     "rapid heartbeat", "persistent cough", "chest pain", 
                     "difficulty breathing", "edema"],
    },
    # Neurology
    {
        "disease": "Migraine",
        "specKey": "neuro",
        "severity": "moderate",
        "description": "Recurring headaches that can be severe and debilitating.",
        "symptoms": ["severe headache", "throbbing headache", "nausea", "vomiting",
                     "sensitivity to light", "sensitivity to sound", "aura", "visual disturbance",
                     "one-sided headache", "migraine"],
    },
    {
        "disease": "Stroke",
        "specKey": "neuro",
        "severity": "emergency",
        "description": "Brain damage caused by interrupted blood flow to the brain.",
        "symptoms": ["sudden numbness", "face drooping", "arm weakness", "speech difficulty",
                     "confusion", "vision problem", "severe headache", "stroke", "paralysis",
                     "slurred speech", "loss of balance"],
    },
    {
        "disease": "Epilepsy",
        "specKey": "neuro",
        "severity": "moderate",
        "description": "A neurological disorder marked by recurrent seizures.",
        "symptoms": ["seizure", "convulsions", "loss of consciousness", "staring spell",
                     "jerking movements", "confusion", "falling", "uncontrolled movements"],
    },
    {
        "disease": "Tension Headache",
        "specKey": "neuro",
        "severity": "mild",
        "description": "The most common type of headache caused by muscle tension.",
        "symptoms": ["headache", "pressure in head", "tight band around head", "neck pain",
                     "shoulder pain", "tender scalp", "mild headache", "dull ache"],
    },
    # Dermatology
    {
        "disease": "Eczema (Atopic Dermatitis)",
        "specKey": "derma",
        "severity": "mild",
        "description": "A condition that makes skin red, inflamed, and itchy.",
        "symptoms": ["itchy skin", "rash", "dry skin", "scaly skin", "inflamed skin",
                     "red patches", "cracked skin", "weeping skin", "eczema", "skin irritation"],
    },
    {
        "disease": "Psoriasis",
        "specKey": "derma",
        "severity": "moderate",
        "description": "A skin disease causing red, itchy scaly patches.",
        "symptoms": ["red patches", "silver scales", "dry cracked skin", "itching", "burning skin",
                     "thickened nails", "swollen joints", "psoriasis", "plaques on skin"],
    },
    {
        "disease": "Acne",
        "specKey": "derma",
        "severity": "mild",
        "description": "A skin condition where hair follicles are clogged with oil and dead skin.",
        "symptoms": ["pimples", "blackheads", "whiteheads", "cysts", "oily skin", "acne",
                     "facial breakout", "painful bumps on face", "scarring"],
    },
    {
        "disease": "Urticaria (Hives)",
        "specKey": "derma",
        "severity": "mild",
        "description": "Itchy welts that appear on the skin due to allergic reactions.",
        "symptoms": ["hives", "welts", "itchy skin", "swelling", "red skin", "urticaria",
                     "allergic reaction", "skin bumps", "burning sensation"],
    },
    # Orthopaedics
    {
        "disease": "Osteoarthritis",
        "specKey": "ortho",
        "severity": "moderate",
        "description": "Degeneration of joint cartilage and the underlying bone.",
        "symptoms": ["joint pain", "stiffness", "swollen joints", "grinding sensation",
                     "limited range of motion", "knee pain", "hip pain", "osteoarthritis",
                     "pain with movement", "joint tenderness"],
    },
    {
        "disease": "Fracture",
        "specKey": "ortho",
        "severity": "moderate",
        "description": "A break or crack in a bone.",
        "symptoms": ["bone pain", "swelling", "bruising", "tenderness", "deformity",
                     "inability to move", "fracture", "broken bone", "severe pain at injury site"],
    },
    {
        "disease": "Lower Back Pain",
        "specKey": "ortho",
        "severity": "mild",
        "description": "Pain in the lumbar region that can be acute or chronic.",
        "symptoms": ["back pain", "lower back pain", "radiating leg pain", "muscle spasm",
                     "stiffness in back", "sciatica", "pain sitting", "pain standing",
                     "numbness in legs","accident","fall from building"],
    },
    # Paediatrics
    {
        "disease": "Chickenpox",
        "specKey": "pedia",
        "severity": "mild",
        "description": "A highly contagious infection causing an itchy blister rash.",
        "symptoms": ["itchy rash", "blisters", "fever", "fatigue", "loss of appetite",
                     "chickenpox", "red spots", "fluid-filled blisters", "scabs"],
    },
    {
        "disease": "Measles",
        "specKey": "pedia",
        "severity": "moderate",
        "description": "A highly contagious viral disease with characteristic rash.",
        "symptoms": ["fever", "cough", "runny nose", "red eyes", "skin rash", "measles",
                     "koplik spots", "high fever", "rash spreading"],
    },
    # Gastroenterology
    {
        "disease": "Gastritis",
        "specKey": "gastro",
        "severity": "mild",
        "description": "Inflammation of the stomach lining.",
        "symptoms": ["abdominal pain", "nausea", "vomiting", "bloating", "indigestion",
                     "burning stomach", "loss of appetite", "gastritis", "stomach ache"],
    },
    {
        "disease": "Gastroenteritis",
        "specKey": "gastro",
        "severity": "mild",
        "description": "Inflammation of the stomach and intestines.",
        "symptoms": ["diarrhea", "vomiting", "nausea", "stomach cramps", "fever",
                     "dehydration", "watery stool", "stomach pain", "food poisoning"],
    },
    {
        "disease": "Irritable Bowel Syndrome",
        "specKey": "gastro",
        "severity": "mild",
        "description": "A common disorder affecting the large intestine.",
        "symptoms": ["abdominal pain", "cramping", "bloating", "gas", "diarrhea", "constipation",
                     "ibs", "irregular bowel", "mucus in stool"],
    },
    # Psychiatry
    {
        "disease": "Depression",
        "specKey": "psych",
        "severity": "moderate",
        "description": "A mood disorder causing persistent sadness and loss of interest.",
        "symptoms": ["sadness", "hopelessness", "loss of interest", "fatigue", "sleep problems",
                     "appetite change", "concentration problems", "depression", "worthlessness",
                     "suicidal thoughts"],
    },
    {
        "disease": "Anxiety Disorder",
        "specKey": "psych",
        "severity": "moderate",
        "description": "Excessive worry and fear that interferes with daily activities.",
        "symptoms": ["anxiety", "excessive worry", "restlessness", "irritability", "muscle tension",
                     "sleep difficulty", "panic attacks", "racing heart", "sweating", "nervousness"],
    },
    # --- Expansion: additional General Medicine diseases ---
    {
        "disease": "COVID-19",
        "specKey": "general",
        "severity": "moderate",
        "description": "A contagious respiratory illness caused by the SARS-CoV-2 virus.",
        "symptoms": ["fever", "dry cough", "fatigue", "loss of taste", "loss of smell", "sore throat",
                     "shortness of breath", "body aches", "headache", "covid"],
    },
    {
        "disease": "Malaria",
        "specKey": "general",
        "severity": "moderate",
        "description": "A mosquito-borne disease caused by a parasite that infects red blood cells.",
        "symptoms": ["high fever", "chills", "sweating", "headache", "muscle pain", "fatigue",
                     "nausea", "vomiting", "malaria"],
    },
    {
        "disease": "Tuberculosis",
        "specKey": "general",
        "severity": "moderate",
        "description": "A bacterial infection that mainly affects the lungs.",
        "symptoms": ["persistent cough", "coughing blood", "chest pain", "weight loss", "night sweats",
                     "fatigue", "loss of appetite", "low grade fever", "tuberculosis"],
    },
    {
        "disease": "Pneumonia",
        "specKey": "general",
        "severity": "moderate",
        "description": "Infection that inflames the air sacs in one or both lungs.",
        "symptoms": ["chest pain", "cough with phlegm", "fever", "chills", "shortness of breath",
                     "fatigue", "rapid breathing", "confusion", "pneumonia"],
    },
    {
        "disease": "Bronchitis",
        "specKey": "general",
        "severity": "mild",
        "description": "Inflammation of the lining of the bronchial tubes.",
        "symptoms": ["persistent cough", "mucus production", "wheezing", "chest tightness",
                     "mild fever", "fatigue", "shortness of breath", "bronchitis"],
    },
    {
        "disease": "Urinary Tract Infection",
        "specKey": "general",
        "severity": "mild",
        "description": "An infection in any part of the urinary system.",
        "symptoms": ["burning urination", "frequent urination", "cloudy urine", "pelvic pain",
                     "urgency to urinate", "lower abdominal pain", "strong smelling urine", "uti"],
    },
    {
        "disease": "Hepatitis A",
        "specKey": "general",
        "severity": "moderate",
        "description": "A liver infection caused by the hepatitis A virus.",
        "symptoms": ["fatigue", "nausea", "vomiting", "abdominal pain", "loss of appetite",
                     "yellow skin", "jaundice", "dark urine", "hepatitis"],
    },
    {
        "disease": "Sinusitis",
        "specKey": "general",
        "severity": "mild",
        "description": "Inflammation of the sinuses causing pressure and congestion.",
        "symptoms": ["facial pain", "nasal congestion", "thick nasal discharge", "headache",
                     "reduced smell", "sinus pressure", "postnasal drip", "sinusitis"],
    },
    # --- Expansion: additional Cardiology diseases ---
    {
        "disease": "Arrhythmia",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "An irregular heartbeat caused by faulty electrical signals in the heart.",
        "symptoms": ["irregular heartbeat", "palpitations", "racing heart", "fluttering in chest",
                     "dizziness", "shortness of breath", "chest discomfort", "fainting", "arrhythmia"],
    },
    {
        "disease": "Deep Vein Thrombosis",
        "specKey": "cardio",
        "severity": "emergency",
        "description": "A blood clot that forms in a deep vein, usually in the leg.",
        "symptoms": ["leg swelling", "leg pain", "warm skin on leg", "red skin on leg",
                     "cramping in leg", "tenderness in leg", "deep vein thrombosis"],
    },
    {
        "disease": "Peripheral Artery Disease",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "Narrowed arteries reduce blood flow to the limbs.",
        "symptoms": ["leg pain while walking", "numbness in legs", "cold feet", "weak pulse in legs",
                     "leg cramps", "slow healing sores", "peripheral artery disease"],
    },
    {
        "disease": "Rheumatic Heart Disease",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "Damage to heart valves caused by rheumatic fever.",
        "symptoms": ["shortness of breath", "chest pain", "fatigue", "swollen joints", "fever",
                     "rapid heartbeat", "rheumatic heart"],
    },
    {
        "disease": "Pericarditis",
        "specKey": "cardio",
        "severity": "moderate",
        "description": "Inflammation of the sac surrounding the heart.",
        "symptoms": ["sharp chest pain", "chest pain worse lying down", "fever", "fatigue",
                     "shortness of breath", "pericarditis"],
    },
    # --- Expansion: additional Neurology diseases ---
    {
        "disease": "Bell's Palsy",
        "specKey": "neuro",
        "severity": "moderate",
        "description": "Sudden weakness or paralysis affecting one side of the face.",
        "symptoms": ["facial drooping", "facial weakness", "drooling", "difficulty closing eye",
                     "loss of taste", "facial pain", "one sided face weakness", "bell's palsy"],
    },
    {
        "disease": "Peripheral Neuropathy",
        "specKey": "neuro",
        "severity": "mild",
        "description": "Damage to peripheral nerves causing weakness and numbness.",
        "symptoms": ["numbness in hands", "numbness in feet", "tingling", "burning pain",
                     "muscle weakness", "sensitivity to touch", "neuropathy"],
    },
    {
        "disease": "Vertigo (Benign Positional Vertigo)",
        "specKey": "neuro",
        "severity": "mild",
        "description": "A false sense of spinning or motion, often triggered by head movement.",
        "symptoms": ["dizziness", "spinning sensation", "loss of balance", "nausea", "vomiting",
                     "vertigo", "unsteadiness"],
    },
    {
        "disease": "Parkinson's Disease",
        "specKey": "neuro",
        "severity": "moderate",
        "description": "A progressive disorder affecting movement due to loss of dopamine-producing neurons.",
        "symptoms": ["tremor", "stiffness", "slow movement", "balance problems", "shaking hands",
                     "muscle rigidity", "parkinsons"],
    },
    {
        "disease": "Meningitis",
        "specKey": "neuro",
        "severity": "emergency",
        "description": "Inflammation of the membranes surrounding the brain and spinal cord.",
        "symptoms": ["stiff neck", "severe headache", "high fever", "sensitivity to light",
                     "confusion", "vomiting", "neck stiffness", "meningitis"],
    },
    # --- Expansion: additional Dermatology diseases ---
    {
        "disease": "Fungal Skin Infection (Ringworm)",
        "specKey": "derma",
        "severity": "mild",
        "description": "A common fungal infection causing a ring-shaped itchy rash.",
        "symptoms": ["itchy rash", "ring shaped rash", "red patches", "scaly skin", "peeling skin",
                     "ringworm", "fungal infection"],
    },
    {
        "disease": "Scabies",
        "specKey": "derma",
        "severity": "mild",
        "description": "A contagious skin infestation caused by tiny mites.",
        "symptoms": ["intense itching", "itching worse at night", "rash", "small blisters",
                     "burrow lines on skin", "scabies"],
    },
    {
        "disease": "Vitiligo",
        "specKey": "derma",
        "severity": "mild",
        "description": "A condition causing loss of skin color in patches.",
        "symptoms": ["white patches on skin", "loss of skin color", "premature graying of hair",
                     "vitiligo", "skin discoloration"],
    },
    {
        "disease": "Contact Dermatitis",
        "specKey": "derma",
        "severity": "mild",
        "description": "Skin inflammation caused by contact with an irritant or allergen.",
        "symptoms": ["red rash", "itching", "burning skin", "blisters", "dry cracked skin",
                     "swelling", "contact dermatitis"],
    },
    {
        "disease": "Cellulitis",
        "specKey": "derma",
        "severity": "moderate",
        "description": "A bacterial skin infection that can spread quickly if untreated.",
        "symptoms": ["red swollen skin", "warm skin", "tenderness", "fever", "skin pain",
                     "spreading redness", "cellulitis"],
    },
    # --- Expansion: additional Orthopaedic diseases ---
    {
        "disease": "Sciatica",
        "specKey": "ortho",
        "severity": "moderate",
        "description": "Pain that radiates along the sciatic nerve from the lower back down the leg.",
        "symptoms": ["radiating leg pain", "lower back pain", "numbness in leg", "tingling in leg",
                     "burning pain in leg", "shooting pain", "sciatica"],
    },
    {
        "disease": "Frozen Shoulder",
        "specKey": "ortho",
        "severity": "mild",
        "description": "Stiffness and pain in the shoulder joint that develops gradually.",
        "symptoms": ["shoulder stiffness", "shoulder pain", "limited shoulder movement",
                     "difficulty raising arm", "frozen shoulder"],
    },
    {
        "disease": "Rheumatoid Arthritis",
        "specKey": "ortho",
        "severity": "moderate",
        "description": "An autoimmune disorder causing joint inflammation and pain.",
        "symptoms": ["joint pain", "joint swelling", "morning stiffness", "fatigue", "warm joints",
                     "symmetrical joint pain", "rheumatoid arthritis"],
    },
    {
        "disease": "Sprain / Strain",
        "specKey": "ortho",
        "severity": "mild",
        "description": "Injury to a ligament (sprain) or muscle/tendon (strain).",
        "symptoms": ["swelling", "bruising", "limited movement", "pain with movement",
                     "muscle spasm", "tenderness", "sprain", "strain"],
    },
    # --- Expansion: additional Paediatric diseases ---
    {
        "disease": "Mumps",
        "specKey": "pedia",
        "severity": "mild",
        "description": "A contagious viral infection that mainly affects the salivary glands.",
        "symptoms": ["swollen salivary glands", "jaw pain", "fever", "headache", "muscle aches",
                     "fatigue", "loss of appetite", "swollen cheeks", "mumps"],
    },
    {
        "disease": "Rubella (German Measles)",
        "specKey": "pedia",
        "severity": "mild",
        "description": "A contagious viral infection with a distinctive red rash.",
        "symptoms": ["mild fever", "skin rash", "swollen lymph nodes", "joint pain", "runny nose",
                     "red eyes", "rubella"],
    },
    {
        "disease": "Whooping Cough (Pertussis)",
        "specKey": "pedia",
        "severity": "moderate",
        "description": "A highly contagious bacterial infection of the respiratory tract.",
        "symptoms": ["severe coughing fits", "whooping sound", "runny nose", "mild fever",
                     "vomiting after coughing", "whooping cough", "pertussis"],
    },
    {
        "disease": "Hand-Foot-Mouth Disease",
        "specKey": "pedia",
        "severity": "mild",
        "description": "A common viral illness in young children causing mouth sores and rash.",
        "symptoms": ["mouth sores", "rash on hands", "rash on feet", "fever", "sore throat",
                     "loss of appetite", "hand foot mouth"],
    },
    {
        "disease": "Croup",
        "specKey": "pedia",
        "severity": "moderate",
        "description": "A childhood respiratory condition causing a barking cough.",
        "symptoms": ["barking cough", "hoarse voice", "difficulty breathing", "stridor", "fever",
                     "croup"],
    },
    # --- Expansion: additional Gastroenterology diseases ---
    {
        "disease": "Peptic Ulcer Disease",
        "specKey": "gastro",
        "severity": "moderate",
        "description": "Open sores that develop on the lining of the stomach or small intestine.",
        "symptoms": ["burning stomach pain", "bloating", "heartburn", "nausea", "indigestion",
                     "dark stool", "peptic ulcer"],
    },
    {
        "disease": "GERD (Acid Reflux)",
        "specKey": "gastro",
        "severity": "mild",
        "description": "Chronic acid reflux that irritates the lining of the esophagus.",
        "symptoms": ["heartburn", "acid reflux", "regurgitation", "chest burning",
                     "difficulty swallowing", "sour taste in mouth", "gerd"],
    },
    {
        "disease": "Constipation",
        "specKey": "gastro",
        "severity": "mild",
        "description": "Infrequent or difficult bowel movements.",
        "symptoms": ["infrequent bowel movements", "hard stool", "straining", "bloating",
                     "abdominal discomfort", "incomplete emptying", "constipation"],
    },
    {
        "disease": "Hemorrhoids",
        "specKey": "gastro",
        "severity": "mild",
        "description": "Swollen veins in the lower rectum and anus.",
        "symptoms": ["rectal bleeding", "itching around anus", "pain during bowel movement",
                     "swelling near anus", "hemorrhoids"],
    },
    {
        "disease": "Appendicitis",
        "specKey": "gastro",
        "severity": "emergency",
        "description": "Inflammation of the appendix that requires prompt treatment.",
        "symptoms": ["sudden abdominal pain", "pain near navel", "pain moving to lower right abdomen",
                     "nausea", "vomiting", "loss of appetite", "fever", "appendicitis"],
    },
    # --- Expansion: additional Psychiatry diseases ---
    {
        "disease": "Panic Disorder",
        "specKey": "psych",
        "severity": "moderate",
        "description": "Recurrent, unexpected panic attacks and fear of future attacks.",
        "symptoms": ["panic attacks", "racing heart", "sweating", "trembling",
                     "shortness of breath", "fear of dying", "chest tightness", "panic disorder"],
    },
    {
        "disease": "Insomnia",
        "specKey": "psych",
        "severity": "mild",
        "description": "Persistent difficulty falling or staying asleep.",
        "symptoms": ["difficulty falling asleep", "waking up at night", "waking up too early",
                     "daytime fatigue", "irritability", "insomnia", "poor concentration"],
    },
    {
        "disease": "PTSD (Post-Traumatic Stress Disorder)",
        "specKey": "psych",
        "severity": "moderate",
        "description": "A mental health condition triggered by experiencing or witnessing a traumatic event.",
        "symptoms": ["flashbacks", "nightmares", "severe anxiety", "avoidance",
                     "intrusive memories", "hypervigilance", "ptsd"],
    },
    {
        "disease": "OCD (Obsessive-Compulsive Disorder)",
        "specKey": "psych",
        "severity": "moderate",
        "description": "A disorder involving unwanted repetitive thoughts and compulsive behaviors.",
        "symptoms": ["intrusive thoughts", "repetitive behaviors", "compulsive checking",
                     "excessive cleaning", "need for symmetry", "ocd"],
    },
]

EMERGENCY_KEYWORDS = [
    # Strong exact phrases only (NO generic words like "pain")
    "crushing chest pain",
    "severe chest pain",
    "heart attack",
    "stroke",
    "face drooping",
    "arm weakness",
    "slurred speech",
    "loss of consciousness",
    "unconscious",
    "seizure",
    "convulsion",
    "cannot breathe",
    "can't breathe",
    "severe breathing difficulty",
    "difficulty breathing",
    "paralysis",
    "suicidal thoughts",
    # New from expanded disease set
    "meningitis",
    "stiff neck",
    "neck stiffness",
    "deep vein thrombosis",
    "appendicitis",
    "severe abdominal pain",
    "coughing blood",
]

SPEC_LABELS = {
    "general": "General Physician",
    "cardio":  "Cardiologist",
    "neuro":   "Neurologist",
    "derma":   "Dermatologist",
    "ortho":   "Orthopaedic Surgeon",
    "pedia":   "Paediatrician",
    "gastro":  "Gastroenterologist",
    "psych":   "Psychiatrist",

}


# """
# Static disease-symptom knowledge base used to train the ML model.
# Each entry: disease name, specKey, severity, list of symptoms/keywords.
# """

# DISEASE_DATA = [
#     # General
#     {
#         "disease": "Common Cold",
#         "specKey": "general",
#         "severity": "mild",
#         "description": "A viral infection of the upper respiratory tract.",
#         "symptoms": ["runny nose", "sore throat", "sneezing", "cough", "mild fever", "congestion",
#                      "headache", "fatigue", "watery eyes", "nasal discharge"],
#     },
#     {
#         "disease": "Influenza (Flu)",
#         "specKey": "general",
#         "severity": "moderate",
#         "description": "A highly contagious viral respiratory illness.",
#         "symptoms": ["high fever", "chills", "body aches", "muscle pain", "fatigue", "headache",
#                      "cough", "sore throat", "runny nose", "vomiting", "diarrhea,"],
#     },
#     {
#         "disease": "Typhoid Fever",
#         "specKey": "general",
#         "severity": "moderate",
#         "description": "A bacterial infection that can spread throughout the body.",
#         "symptoms": ["sustained fever", "weakness", "abdominal pain", "headache", "loss of appetite",
#                      "diarrhea", "constipation", "rose spots", "enlarged spleen"],
#     },
#     {
#         "disease": "Dengue Fever",
#         "specKey": "general",
#         "severity": "moderate",
#         "description": "A mosquito-borne viral infection causing severe flu-like illness.",
#         "symptoms": ["high fever", "severe headache", "pain behind eyes", "joint pain", "muscle pain",
#                      "rash", "mild bleeding", "nausea", "vomiting", "bone pain", "dengue"],
#     },
#         {
#         "disease": "Influenza (Flu)",
#         "specKey": "general",
#         "severity": "moderate",
#         "description": "A highly contagious viral respiratory illness.",
#         "symptoms": ["high fever", "chills", "body aches", "muscle pain", "fatigue", "headache",
#                      "cough", "sore throat", "runny nose", "vomiting", "diarrhea,"],
#     },
#     {
#     "disease": "Food Poisoning",
#     "specKey": "general",
#     "severity": "mild",
#     "description": "Illness caused by contaminated food or drink.",
#     "symptoms": [
#         "nausea", "vomiting",  "diarrhea","diarrhea","stomach pain", "abdominal cramps",]
# },
# {
#     "disease": "Electric Shock",
#     "specKey": "general",
#     "severity": "moderate",
#     "description": "Injury caused by electric current.",
#     "symptoms": [
#         "electric shock","electrik shock","burn","pain","muscle pain"],
# },
#     # Cardiology
#     {
#         "disease": "Hypertension (High Blood Pressure)",
#         "specKey": "cardio",
#         "severity": "moderate",
#         "description": "Persistently elevated blood pressure in the arteries.",
#         "symptoms": ["headache", "dizziness", "blurred vision", "chest pain", "shortness of breath",
#                      "high blood pressure", "nose bleed", "palpitations"],
#     },
#     {
#         "disease": "Heart Attack",
#         "specKey": "cardio",
#         "severity": "emergency",
#         "description": "Blockage of blood flow to the heart muscle.",
#         "symptoms": ["chest pain", "crushing chest pain", "left arm pain", "jaw pain",
#                      "shortness of breath", "sweating", "nausea", "dizziness", "heart attack",
#                      "chest pressure", "pain radiating"],
#     },
#     {
#         "disease": "Angina",
#         "specKey": "cardio",
#         "severity": "moderate",
#         "description": "Chest pain caused by reduced blood flow to the heart.",
#         "symptoms": ["chest pain", "tightness in chest", "pressure in chest", "pain in shoulder",
#                      "pain in arm", "shortness of breath", "dizziness", "nausea", "fatigue"],
#     },
#     {
#         "disease": "Heart Failure",
#         "specKey": "cardio",
#         "severity": "emergency",
#         "description": "The heart does not pump blood as well as it should.",
#         "symptoms": ["shortness of breath", "swollen legs", "swollen ankles", "fatigue",
#                      "rapid heartbeat", "persistent cough", "chest pain", 
#                      "difficulty breathing", "edema"],
#     },
#     # Neurology
#     {
#         "disease": "Migraine",
#         "specKey": "neuro",
#         "severity": "moderate",
#         "description": "Recurring headaches that can be severe and debilitating.",
#         "symptoms": ["severe headache", "throbbing headache", "nausea", "vomiting",
#                      "sensitivity to light", "sensitivity to sound", "aura", "visual disturbance",
#                      "one-sided headache", "migraine"],
#     },
#     {
#         "disease": "Stroke",
#         "specKey": "neuro",
#         "severity": "emergency",
#         "description": "Brain damage caused by interrupted blood flow to the brain.",
#         "symptoms": ["sudden numbness", "face drooping", "arm weakness", "speech difficulty",
#                      "confusion", "vision problem", "severe headache", "stroke", "paralysis",
#                      "slurred speech", "loss of balance"],
#     },
#     {
#         "disease": "Epilepsy",
#         "specKey": "neuro",
#         "severity": "moderate",
#         "description": "A neurological disorder marked by recurrent seizures.",
#         "symptoms": ["seizure", "convulsions", "loss of consciousness", "staring spell",
#                      "jerking movements", "confusion", "falling", "uncontrolled movements"],
#     },
#     {
#         "disease": "Tension Headache",
#         "specKey": "neuro",
#         "severity": "mild",
#         "description": "The most common type of headache caused by muscle tension.",
#         "symptoms": ["headache", "pressure in head", "tight band around head", "neck pain",
#                      "shoulder pain", "tender scalp", "mild headache", "dull ache"],
#     },
#     # Dermatology
#     {
#         "disease": "Eczema (Atopic Dermatitis)",
#         "specKey": "derma",
#         "severity": "mild",
#         "description": "A condition that makes skin red, inflamed, and itchy.",
#         "symptoms": ["itchy skin", "rash", "dry skin", "scaly skin", "inflamed skin",
#                      "red patches", "cracked skin", "weeping skin", "eczema", "skin irritation"],
#     },
#     {
#         "disease": "Psoriasis",
#         "specKey": "derma",
#         "severity": "moderate",
#         "description": "A skin disease causing red, itchy scaly patches.",
#         "symptoms": ["red patches", "silver scales", "dry cracked skin", "itching", "burning skin",
#                      "thickened nails", "swollen joints", "psoriasis", "plaques on skin"],
#     },
#     {
#         "disease": "Acne",
#         "specKey": "derma",
#         "severity": "mild",
#         "description": "A skin condition where hair follicles are clogged with oil and dead skin.",
#         "symptoms": ["pimples", "blackheads", "whiteheads", "cysts", "oily skin", "acne",
#                      "facial breakout", "painful bumps on face", "scarring"],
#     },
#     {
#         "disease": "Urticaria (Hives)",
#         "specKey": "derma",
#         "severity": "mild",
#         "description": "Itchy welts that appear on the skin due to allergic reactions.",
#         "symptoms": ["hives", "welts", "itchy skin", "swelling", "red skin", "urticaria",
#                      "allergic reaction", "skin bumps", "burning sensation"],
#     },
#     # Orthopaedics
#     {
#         "disease": "Osteoarthritis",
#         "specKey": "ortho",
#         "severity": "moderate",
#         "description": "Degeneration of joint cartilage and the underlying bone.",
#         "symptoms": ["joint pain", "stiffness", "swollen joints", "grinding sensation",
#                      "limited range of motion", "knee pain", "hip pain", "osteoarthritis",
#                      "pain with movement", "joint tenderness"],
#     },
#     {
#         "disease": "Fracture",
#         "specKey": "ortho",
#         "severity": "moderate",
#         "description": "A break or crack in a bone.",
#         "symptoms": ["bone pain", "swelling", "bruising", "tenderness", "deformity",
#                      "inability to move", "fracture", "broken bone", "severe pain at injury site"],
#     },
#     {
#         "disease": "Lower Back Pain",
#         "specKey": "ortho",
#         "severity": "mild",
#         "description": "Pain in the lumbar region that can be acute or chronic.",
#         "symptoms": ["back pain", "lower back pain", "radiating leg pain", "muscle spasm",
#                      "stiffness in back", "sciatica", "pain sitting", "pain standing",
#                      "numbness in legs","accident","fall from building"],
#     },
#     # Paediatrics
#     {
#         "disease": "Chickenpox",
#         "specKey": "pedia",
#         "severity": "mild",
#         "description": "A highly contagious infection causing an itchy blister rash.",
#         "symptoms": ["itchy rash", "blisters", "fever", "fatigue", "loss of appetite",
#                      "chickenpox", "red spots", "fluid-filled blisters", "scabs"],
#     },
#     {
#         "disease": "Measles",
#         "specKey": "pedia",
#         "severity": "moderate",
#         "description": "A highly contagious viral disease with characteristic rash.",
#         "symptoms": ["fever", "cough", "runny nose", "red eyes", "skin rash", "measles",
#                      "koplik spots", "high fever", "rash spreading"],
#     },
#     # Gastroenterology
#     {
#         "disease": "Gastritis",
#         "specKey": "gastro",
#         "severity": "mild",
#         "description": "Inflammation of the stomach lining.",
#         "symptoms": ["abdominal pain", "nausea", "vomiting", "bloating", "indigestion",
#                      "burning stomach", "loss of appetite", "gastritis", "stomach ache"],
#     },
#     {
#         "disease": "Gastroenteritis",
#         "specKey": "gastro",
#         "severity": "mild",
#         "description": "Inflammation of the stomach and intestines.",
#         "symptoms": ["diarrhea", "vomiting", "nausea", "stomach cramps", "fever",
#                      "dehydration", "watery stool", "stomach pain", "food poisoning"],
#     },
#     {
#         "disease": "Irritable Bowel Syndrome",
#         "specKey": "gastro",
#         "severity": "mild",
#         "description": "A common disorder affecting the large intestine.",
#         "symptoms": ["abdominal pain", "cramping", "bloating", "gas", "diarrhea", "constipation",
#                      "ibs", "irregular bowel", "mucus in stool"],
#     },
#     # Psychiatry
#     {
#         "disease": "Depression",
#         "specKey": "psych",
#         "severity": "moderate",
#         "description": "A mood disorder causing persistent sadness and loss of interest.",
#         "symptoms": ["sadness", "hopelessness", "loss of interest", "fatigue", "sleep problems",
#                      "appetite change", "concentration problems", "depression", "worthlessness",
#                      "suicidal thoughts"],
#     },
#     {
#         "disease": "Anxiety Disorder",
#         "specKey": "psych",
#         "severity": "moderate",
#         "description": "Excessive worry and fear that interferes with daily activities.",
#         "symptoms": ["anxiety", "excessive worry", "restlessness", "irritability", "muscle tension",
#                      "sleep difficulty", "panic attacks", "racing heart", "sweating", "nervousness"],
#     },
# ]

# EMERGENCY_KEYWORDS = [
#     # Strong exact phrases only (NO generic words like "pain")
#     "crushing chest pain",
#     "severe chest pain",
#     "heart attack",
#     "stroke",
#     "face drooping",
#     "arm weakness",
#     "slurred speech",
#     "loss of consciousness",
#     "unconscious",
#     "seizure",
#     "convulsion",
#     "cannot breathe",
#     "can't breathe",
#     "severe breathing difficulty",
#     "paralysis",
#     "suicidal thoughts"
# ]

# SPEC_LABELS = {
#     "general": "General Physician",
#     "cardio":  "Cardiologist",
#     "neuro":   "Neurologist",
#     "derma":   "Dermatologist",
#     "ortho":   "Orthopaedic Surgeon",
#     "pedia":   "Paediatrician",
#     "gastro":  "Gastroenterologist",
#     "psych":   "Psychiatrist",

# }



